name: Roblox Yüzlerini Otomatik İndir

on:
  workflow_dispatch: # Manuel tetikleme butonu

permissions:
  contents: write # Repoya dosya yazma izni

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repoyu Klonla
      uses: actions/checkout@v4

    - name: Python Kur
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Kütüphaneleri Yükle
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Python Scriptini Çalıştır
      run: python indirici.py

    - name: Değişiklikleri Güvenli Şekilde Commit Et ve Gönder
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add yuzler/
        
        # Eğer değişen bir şey yoksa çökmesini engellemek için '|| exit 0' ekliyoruz
        git commit -m "Roblox yüzleri gerçek fotoğraflara dönüştürüldü" || exit 0
        
        # Gönderirken çakışma (conflict) olmasın diye pull yapıp sonra pushluyoruz
        git pull --rebase
        git push
